data:
  num_classes: 100
  loader:
    batch_size: 512

model_type: 'ResNet'
model_size: 'ResNet18'
norm_type: 'frob'
hparas:                                   # Experiment hyper-parameters
  epochs: 50
