data:
  num_classes: 100
  corpus:
    n_talkers: [1,5]
    with_audioset: True
    root: '/om2/user/msaddler/projects/ibmHearingAid/assets/data/datasets/JSIN_v3.00/nStim_20000/2000ms/rms_0.1/noiseSNR_-10_10/stimSR_20000/reverb_none/noise_all/JSIN_all_v3/subsets/' # Path to raw GigaSpeech dataset
  image:                                  # Attributes of image feature
    rep_type:  'cochlea_filt'
    rep_kwargs:
      size: 32
      env_sr: 8000
      n_channels: 3
      low_lim: 40
      use_pad: True
      rep_on_gpu: False
      env_extraction_type: 'Half-wave Rectification'
      downsampling_type: 'TorchTransformsResample'
      downsampling_kwargs:
        lowpass_filter_width: 64
        rolloff: 0.9475937167399596
        resampling_method: "kaiser_window"
        beta: 14.769656459379492
  loader:
    batch_size: 256 

val_metric: 
  train_acc: 'train_acc'
  val_acc: 'val_acc'
model_name: 'ResNet18_NoNorm'
layernorm_first: False
batchnorm: False
hparas:                                   # Experiment hyper-parameters
  valid_step: 5000
  epochs: 20
  optimizer: 'Adam'
  lr: 0.0001
  eps: 0.00000001                         # 1e-8
  lr_scheduler: 'fixed'                   # 'fixed'/'warmup'
  curriculum: 0
  gradient_clip_val: 100 
