data:
  num_classes: 100
  loader:
    batch_size: 512

model_type: 'MLP'
num_layers: 10
width: 4000
norm_type: 'baseline'
hparas:                                   # Experiment hyper-parameters
  epochs: 200
  lr: .001
