data:
  num_classes: 100
  loader:
    batch_size: 512

model_type: 'MLP'
num_layers: 5
width: 2000
norm_type: 'spec'
hparas:                                   # Experiment hyper-parameters
  epochs: 200
