data:
  num_classes: 100
  loader:
    batch_size: 512

model_type: 'MLP'
num_layers: 20
width: 8000
norm_type: 'baseline'
hparas:                                   # Experiment hyper-parameters
  epochs: 200
